### PR TITLE
feat: Redmine Support

### PR DESCRIPTION
**Pull request by huygun**
Redmine issue tracker support added

### CODE REVIEW

**Comment by tomasbjerre** [comment]
Thanks, looks good! There are failing tests when I run `./gradlew build`.

Make sure you:

 * Inspect the changes in `*.approved.txt`-files, make sure it is reasonable. Looks like some Github-issues are now identified as Redmine, probably better to not match both Github and Redmine with same pattern in the test cases setup.
 * Commit the approved files.

**Comment by huygun** [comment]
I'm not sure how can manage test cases. Maybe I can add additional test scenarios for Redmine.  Because issue pattern is same as GitGub/GitLab's. Also I dont want to break current tests :)

**Comment by tomasbjerre** [comment]
I can probably fix it tomorrow. Putting this on my TODO.

**Comment by tomasbjerre** [comment]
Released as 1.159.0

**Pull request merged**
