### PR TITLE
feat: Add support for defining Javascript helpers in a separate file

### PR DESCRIPTION
**Pull request by chme**
It would be nice to be able to define the Javascript Handlebars helpers in a separate file.
For the maven plugin, this will have the benefit of not having to put Javascript code into the pom.xml.

### CODE REVIEW

**Comment by tomasbjerre** [comment]
Or you can just do:
ResourceLoader.getResourceOrFile(javascriptHelperFile);
In the maven plugin, right?

I dont see much value in adding an extra method here. But sounds like a good feature to have in the maven plugin.

**Comment by chme** [comment]
I thought the command line program would also benefit from reading the helpers from a file.
If I understood it correctly, with the cli you have to pass the Javascript code as an option `--register-handlebars-helper`.
This change would allow it to pass the filename of the JS-file instead.

**Comment by tomasbjerre** [comment]
Also sounds like a good feature.
But I would just do:
String content = Files.readString(Parhs.get(filename), StandardCharsets.US_ASCII)
And supply that to the library.

I dont see that this library needa to help reading files.

**Comment by tomasbjerre** [comment]
Adding `handlebarsHelperFile` to the maven plugin:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/src/main/java/se/bjurr/gitchangelog/plugin/GitChangelogMojo.java#L157

And in the command line tool:
https://github.com/tomasbjerre/git-changelog-command-line/blob/master/src/main/java/se/bjurr/gitchangelog/main/Main.java#L468

**Pull request closed without merging**
